version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2017
environment:
  CODECOV_TOKEN-uuid: 09262c97-8841-4e52-a22c-2ba7a3e17e41
nuget:
  disable_publish_on_pr: true
build_script:
- ps: >-
    .\build.ps1 -Target CiBuild --settings_skipverification=true
test: off
deploy:
  provider: environment
  mame: deploy-x86
  artifact: ./artifacts*.*
  on:
    branch: master
    platform: x86
    configuration: release
  provider: environment
  mame: deploy-x64
  artifact: ./artifacts*.*
  on:
    branch: master
    platform: x64
    configuration: release
notifications:
- provider: Email
  to:
  - gustavo.adolph@gmail.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false